### ISSUE TITLE
RSpec v3 is not supported

### ISSUE THREAD

**Issue by grdmnt** [collectiveidea/interactor-rails#21]
Current spec generator requires 'spec_helper' while RSpec v3 requires 'rails_helper'

From [RSpec Rails GitHub](https://github.com/rspec/rspec-rails)

<img width="640" alt="screen shot 2018-07-10 at 1 29 10 pm" src="https://user-images.githubusercontent.com/10776105/42490957-4d04119e-8445-11e8-9498-f04fa3dfb084.png">

**Comment by fzf** [comment]
@laserlemon https://github.com/collectiveidea/interactor-rails/pull/27 should fix this issue

**Comment by gaffneyc** [comment]
Fixed by 0a6361456ed53e5b492c68916a19860ce21f68eb
