### ISSUE TITLE
Test::Unit not supported

### ISSUE THREAD

**Issue by kmcd** [collectiveidea/interactor-rails#22]
The generator only generates spec files &mdash; I _hate_ rspec 😄 . 

Any chance you could support plain old `Test::Unit` before I submit a PR?

**Comment by gaffneyc** [comment]
We would absolutely love a pull request to add Test::Unit support. We use Rspec for pretty much everything internally so it's unlikely that we'll implement this ourselves.

**Comment by ukazap** [comment]
Hi @gaffneyc, I've submitted a PR for this: https://github.com/collectiveidea/interactor-rails/pull/32
