### ISSUE TITLE
I think this needs updating to be compatible with Rails 6

### ISSUE THREAD

**Issue by HenryHaller** [collectiveidea/interactor-rails#23]
I'm trying to upgrade an app to rails 6 and I get this:
```
 bundle update rails
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies..........
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 6.0.0.beta1)

    interactor-rails (~> 2.0) was resolved to 2.2.0, which depends on
      rails (>= 4.2, < 5.3)
```

**Comment by ianjhuang** [comment]
@HenryHaller did you finding a way around this?

**Comment by galileoguzman** [comment]
@ianjhuang @HenryHaller 

Hey guys!!!

I am using Rails 6 in a project and I wanted to use interactor-rails but I got the same error though I found a way to work with it.

I use the original gem

`gem "interactor", "~> 3.0"`

Then in `config/application.rb` I required the gem

`require "interactor"`

and works perfectly to me

**Comment by fauxparse** [comment]
See #25

**Comment by gaffneyc** [comment]
Duplicate #25
