### ISSUE TITLE
Support to Rails 6.0.0

### ISSUE THREAD

**Issue by memoxmrdl** [collectiveidea/interactor-rails#28]

**Comment by fauxparse** [comment]
See #25

**Comment by MajedBojan** [comment]
I'm trying to upgrade my project into rails 6 and the project has huge dependencies on this this gem but still the gem not compatible with rails 6

```Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 6.0.0.rc2)

    interactor-rails (~> 2.0) was resolved to 2.2.0, which depends on
      rails (>= 4.2, < 5.3)
```

**Comment by memoxmrdl** [comment]
@MajedBojan You can install only `interactor` gem and add the `require "interactor"` from file `config/application.rb` and that it works good.

**Comment by gaffneyc** [comment]
Just waiting on a release which will probably have to wait until next week once the holiday weekend is over.

@laserlemon Would you mind adding me to rubygems.org so I can publish the new version?
