### ISSUE TITLE
rails generate interactor should create a spec or test file

### ISSUE THREAD

**Issue by albus522** [collectiveidea/interactor-rails#3]
The generator should also create an appropriate spec or test file.
We are fans of TDD here.

**Comment by scottrobertson** [comment]
:+1:

**Comment by posgarou** [comment]
:+1:

**Comment by Kukunin** [comment]
:+1:

**Comment by JDutil** [comment]
Please review https://github.com/collectiveidea/interactor-rails/pull/11
