### ISSUE TITLE
uninitialized constant Admin::UsersController::CreateLoyalty

### ISSUE THREAD

**Issue by kuzevanoff** [collectiveidea/interactor-rails#30]
Hi,
I have:
/admin/users_controller.rb
```
class Admin::UsersController < AdminController
def update
    CreateLoyalty.call( user: @user, portals: params[ :portals ] )
end
```
/interactors/admin/create_loyalty.rb
```
  def call
    context.user.user_portals.destroy_all
    unless context.portals.blank?
      context.portals.each do | c |
        UserPortal.create user: context.user, portal_id: c
      end
    end
  end
```
Why I get this error? 

Thanks

**Comment by kuzevanoff** [comment]
UPDT:
if I shut down rails server and than start it - it works fine, but sometimes I have this error. restart server help me.
so it seems that rails can't load classes.
ruby 2.4.1p111
Rails 5.1.7

**Comment by gaffneyc** [comment]
You'll likely need to add the interactors directory to your Rails auto load path as it's unable to find the file to load for. I'm not seeing anything here that is an issue with interactor-rails itself.
